name: ci

on:
  schedule:
    - cron: "* 0 * * *"
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Import image
        run: docker import https://dl.carbslinux.org/releases/x86_64/carbs-rootfs.tar.xz carbslinux2/carbslinux
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: carbslinux2/carbslinux
